### ISSUE TITLE
DHCP Role Fails - Undefined variable other

### ISSUE THREAD

**Issue by ghost** [edigitalresearch/ansible-role-dhcp#1]
@lewiscarhartmaru DHCP role fails when applying against an environment

```
{"msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'other'"}
```
Looks to do with the shift in the lease time to the globals key - Could you fork and open a PR for this?
Thanks!

**Comment by lewis-carhart** [comment]
My PR has been merged. @maruedr-dylanrhysscott give it a test and let me know the outcome and I'll close this issue off.

**Comment by ghost** [comment]
Fix in the end was to ensure `hash_behaviour=merge` is set in the global `ansible.cfg`. This has now fixed. Closing.
